const PAGES = {
  about: {
    title: "About ShieldPick",
    metaTitle: "About ShieldPick — Independent VPN Reviews",
    metaDesc: "ShieldPick is an independent VPN review site. We test every VPN ourselves and publish honest, unbiased results.",
    content: `<h2>Who We Are</h2><p>ShieldPick is an independent VPN review site founded in 2026. We test VPNs ourselves — measuring speed, security, streaming access, and value — so you can make an informed decision about your online privacy.</p><h2>Our Mission</h2><p>The VPN market is full of sponsored rankings and misleading claims. We believe everyone deserves honest reviews based on real testing, not marketing budgets. Every VPN we review goes through the same standardized testing process, and our results are published transparently.</p><h2>How We Make Money</h2><p>ShieldPick is reader-supported. When you click an affiliate link and purchase a VPN, we may earn a commission at no extra cost to you. <strong>Affiliate relationships never influence our rankings or scores.</strong> We've given low scores to VPNs with high commissions and recommended VPNs with no affiliate program. Our reputation depends on honest reviews.</p><h2>Contact</h2><p>Questions, corrections, or suggestions: <strong>hello@shieldpick.com</strong></p>`
  },
  methodology: {
    title: "How We Test VPNs",
    metaTitle: "How We Test VPNs — Our Testing Methodology | ShieldPick",
    metaDesc: "Every VPN on ShieldPick is tested using standardized methodology. Speed tests, leak detection, streaming access, and security audits.",
    content: `<h2>Our Testing Methodology</h2><p>Every VPN reviewed on ShieldPick goes through rigorous, standardized testing. We don't just read spec sheets — we install, configure, and use every VPN ourselves over a minimum of 2 weeks.</p><h2>Scoring Criteria</h2><div class="table-wrap"><table><thead><tr><th>Criteria</th><th>Weight</th><th>What We Test</th></tr></thead><tbody><tr><td class="product-name">Speed</td><td class="score">25%</td><td>Download/upload to 10+ locations via Ookla Speedtest</td></tr><tr><td class="product-name">Security</td><td class="score">25%</td><td>Encryption, DNS/WebRTC leak tests, kill switch</td></tr><tr><td class="product-name">Privacy</td><td class="score">20%</td><td>Logging policy, audits, jurisdiction</td></tr><tr><td class="product-name">Streaming</td><td class="score">15%</td><td>Netflix, Disney+, BBC iPlayer, Hulu, Prime unblocking</td></tr><tr><td class="product-name">Value</td><td class="score">15%</td><td>Price, device limits, features, guarantee</td></tr></tbody></table></div><h2>Speed Testing</h2><p>All tests run on a 1 Gbps fiber connection, Windows 11, using Ookla Speedtest. Each VPN tested 3+ times per location at different times of day. Locations: US, UK, Germany, Japan, Australia, Singapore, Canada, Netherlands, Brazil.</p><h2>Security Testing</h2><p>DNS leak tests via browserleaks.com and dnsleaktest.com. WebRTC leak tests in Chrome, Firefox, Edge. Kill switch tested by forcing connection drops and monitoring for IP exposure via Wireshark.</p><h2>Re-Testing</h2><p>All VPNs are re-tested monthly. Speeds change, features update, prices shift — our reviews reflect current reality.</p><h2>Editorial Independence</h2><p>No VPN company can pay for a higher ranking. Our editorial team has final say on all scores. We've declined partnerships that requested editorial influence.</p>`
  },
  privacy: {
    title: "Privacy Policy",
    metaTitle: "Privacy Policy | ShieldPick",
    metaDesc: "ShieldPick's privacy policy. We collect minimal data and never sell your information.",
    content: `<p><em>Last updated: March 2026</em></p><h2>Information We Collect</h2><p><strong>Analytics:</strong> Privacy-respecting analytics to understand which articles are helpful. Aggregated, non-identifying.</p><p><strong>Email:</strong> If you subscribe to our newsletter, we collect your email. You can unsubscribe anytime.</p><p><strong>Cookies:</strong> Essential cookies for site functionality and affiliate tracking. No advertising cookies.</p><h2>Affiliate Links</h2><p>When you click an affiliate link, the affiliate network may place a cookie to track the referral. This is standard for affiliate marketing and is how we fund our testing.</p><h2>Your Rights</h2><p>You can: access your data, request deletion, unsubscribe from emails, and opt out of cookies via browser settings.</p><h2>Contact</h2><p>Privacy questions: <strong>privacy@shieldpick.com</strong></p>`
  },
  disclosure: {
    title: "Affiliate Disclosure",
    metaTitle: "Affiliate Disclosure | ShieldPick",
    metaDesc: "How ShieldPick makes money through affiliate commissions and why it doesn't affect our reviews.",
    content: `<h2>How ShieldPick Makes Money</h2><p>ShieldPick is free for readers. We earn money through affiliate commissions when you purchase a VPN through our links, at <strong>no additional cost to you</strong>.</p><h2>Our Affiliate Partners</h2><p>We currently have affiliate relationships with: NordVPN, Surfshark, ExpressVPN, and ProtonVPN. This list may change. We also review VPNs that have no affiliate program.</p><h2>Does This Affect Our Reviews?</h2><p><strong>No.</strong> Rankings and scores are based solely on our testing results. We have given low scores to VPNs with lucrative affiliate programs. Our reputation and business depend on honest reviews.</p><h2>FTC Compliance</h2><p>This disclosure is provided in accordance with FTC guidelines on endorsements and testimonials. All articles containing affiliate links include a disclosure notice.</p>`
  },
  deals: {
    title: "Best VPN Deals — March 2026",
    metaTitle: "Best VPN Deals March 2026 — Biggest Discounts | ShieldPick",
    metaDesc: "The best VPN deals and discounts for March 2026. Save up to 87% on top-rated VPNs. Updated weekly.",
    content: `<p>We track the best VPN deals so you don't have to. All prices verified and updated weekly.</p><div class="product-box"><div class="product-rank">🔥</div><div class="product-info"><h3>NordVPN — 74% Off</h3><div class="product-subtitle">#1 Rated VPN — Best Overall Deal</div><p>2-year plan at <strong>$3.39/month</strong> (was $12.99). Includes Threat Protection, 7,200+ servers, 10 devices, and 30-day money-back guarantee. Score: 9.6/10</p><a href="#affiliate" class="btn-aff">Get NordVPN Deal →</a></div></div><div class="product-box"><div class="product-rank">💰</div><div class="product-info"><h3>Surfshark — 87% Off</h3><div class="product-subtitle">Best Value — Unlimited Devices</div><p>2-year plan at <strong>$1.99/month</strong> (was $15.45). Unlimited devices, CleanWeb ad blocker, 30-day money-back guarantee. Score: 9.2/10</p><a href="#affiliate" class="btn-aff">Get Surfshark Deal →</a></div></div><div class="product-box"><div class="product-rank">⚡</div><div class="product-info"><h3>ExpressVPN — 73% Off</h3><div class="product-subtitle">Best for Streaming</div><p>1-year plan at <strong>$3.49/month</strong> (was $12.95). Unblocks every streaming platform. 30-day money-back guarantee. Score: 9.0/10</p><a href="#affiliate" class="btn-aff">Get ExpressVPN Deal →</a></div></div><div class="product-box"><div class="product-rank">🔒</div><div class="product-info"><h3>ProtonVPN — 50% Off</h3><div class="product-subtitle">Best for Privacy</div><p>2-year plan at <strong>$3.99/month</strong>. Swiss-based, open source, independently audited. Has a legitimate free tier. Score: 8.8/10</p><a href="#affiliate" class="btn-aff">Get ProtonVPN Deal →</a></div></div><p style="margin-top:32px;padding:16px;background:rgba(0,229,160,0.08);border:1px solid rgba(0,229,160,0.2);border-radius:8px;font-size:13px;color:#00E5A0;"><strong>Tip:</strong> All VPNs above offer 30-day money-back guarantees. Test risk-free and get a full refund if not satisfied.</p>`
  }
};

export default PAGES;
